server:
  port: 8087

spring:
  main:
    allow-bean-definition-overriding: true
  ai:
    openai:
      api-key: ${qwen}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen3.5-plus
          temperature: 0.7
    mcp:
      client:
        sse:
          connections:
            mcp-server1:
              url: http://localhost:8086
        type: async
        toolcallback:
          enabled: true
